version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - /app/node_modules
      - .:/app
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]